### ISSUE TITLE
Update Glpi 9.5.2 and use generic object 2.9.0 - Dropdown disappeared

### ISSUE THREAD

**Issue by rpauleau** [pluginsGLPI/genericobject#297] opened 2020-10-22 15:39 UTC
Hi,

I update my glpi lab (test) on 9.5.2 version but when I use the new version of generic object 2.9.0 my dropdown disappear.
have you ever had this kind of case?

Regards

**Comment by rpauleau** [comment] 2020-10-23 07:14
before
![before](https://user-images.githubusercontent.com/60617115/96967302-98f7c700-150f-11eb-8762-1b0955ac9b2a.png)

after
![after](https://user-images.githubusercontent.com/60617115/96967320-a01ed500-150f-11eb-825b-51a5b0f5cac2.png)

on the file syntax no change, is the same thing
field.constant.php

**Comment by J-C-P** [comment] 2020-10-29 09:34
Have a look at your locale file.
Check if the french is there and complete.

**Comment by rpauleau** [comment] 2020-10-29 16:45
Yes 2 files (*.mo & *.po) are present and whole here => /var/www/glpi/plugins/genericobject/locales/

**Comment by Aerandir34** [comment] 2020-11-04 21:52
Hello,

Seems related to php version.
with GLPI server 9.5.2 & GenericObject vers 2.9.1:

Ubuntu server 20.04 LTS (php 7.4) > no dropdown menu at all (tried multi glpi/genericObject version)
rollback to Ubuntu server 18.04 LTS (php7.2) > ok
Debian 10 (php7.3) > ok

**Comment by rpauleau** [comment] 2020-11-05 13:35
Ah ! Thank you !

You know if it's possible to tell the plugin to use another version of php ?

**Comment by rpauleau** [comment] 2020-11-06 15:29
I will wait 7.4 support for this plugin I think

**Comment by cedric-anne** [comment] 2020-11-09 08:20
Hi,

Is there some logs related to this issue (in GLPI logs or in browser console) ?

Regards

**Comment by okvok** [comment] 2020-11-09 16:13
GLPI 9.4.6+GenericObeject 2.8.0 + php 7.4.12 = OK
GLPI 9.5.2+GenericObeject 2.9.1 + php 7.4.12 = not OK

**Comment by OscarBeiro** [comment] 2020-11-17 08:37
Hi,

This seems to be related to the DB, not PHP or GLPI.

Generic object is using type int(11) for dropdown fields. Since MySQL 8.0.17, documented on 8.0.19, Int size is deprecated. Due to this behaviour alteration, GLPI cannot read an int(11) , and considers data a string, resulting in a dropdown not been shown.
When altering manually a table field you get a:

`Warning  1681  Integer display width is deprecated and will be removed in a future release.`

We have discovered this issue on a testing Percona instance, but affects MySQL and probably MariaDB (not confirmed).

This is an important issue, that should be addressed in this plugin and maybe others like Formcreator, and Additional Fields.

More information on that, here: https://stackoverflow.com/questions/60892749/mysql-8-ignoring-integer-lengths

Thanks to @xacobofg for discovering this issue.

**Comment by cedric-anne** [comment] 2020-11-17 13:01
Hi,

Thanks @OscarBeiro for your analysis.

#300 should fix this issue.

@rpauleau @okvok @Aerandir34 @OscarBeiro , could you confirm ?

Regards

**Comment by xacobofg** [comment] 2020-11-17 13:28
Hi @cedric-anne .
I have tried the solution #300  and it works

**Comment by okvok** [comment] 2020-11-18 15:23
For me it doesn't work.
Operating system: Linux bd-sd11.gpnbadra.local 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64
PHP 7.4.12 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, bcmath, bz2, calendar, cgi-fcgi,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mbstring,
	mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, recode, session, shmop, soap, sockets, sodium, sqlite3,
	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="1024M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="5M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_auth_kerb/5.4 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 Edg/86.0.622.69
Server Software: MariaDB Server
	Server Version: 10.4.17-MariaDB
	Server SQL Mode: 
	Parameters: glpidb@localhost/db_glpi_prod
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is installedCAS extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.4.17) - Perfect!Database version seems correct (10.4.17) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/glpi/config has been validated.Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files has been validated.Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_cron has been validated.Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_cache has been validated.Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/files/_rss has been validated.Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.Write access to /var/www/glpi/files/_uploads has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/marketplace has been validated.Write access to /var/www/glpi/marketplace has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
SELinux configuration is OK.SELinux configuration is OK.

**Comment by cedric-anne** [comment] 2020-11-18 15:26
@okvok As your are using MariaDB, your problem may be due to something else.

**Comment by okvok** [comment] 2020-11-19 05:14
In my case it can open dropdown list only if assets are located in parent entity with an option  "Child entities" set  "Yes".
In case assets located at the same entity with a ticket - dropdown list does not show. 
This bug appeared from glpi 9.5.2 and GenericObject 2.9.1

**Comment by okvok** [comment] 2020-11-19 06:12
After investigation I found the filed "is_helpdesk_visible" had been set to 0. So I suppose the reason of my issue.
Could some help to clarify where I can set it back to 1 in GLPI IU except sql query?
Thanks

**Comment by cedric-anne** [comment] 2020-11-19 07:54
> After investigation I found the filed "is_helpdesk_visible" had been set to 0. So I suppose the reason of my issue.
> Could some help to clarify where I can set it back to 1 in GLPI IU except sql query?
> Thanks

1. `Use Assistance` should be checked in your object configuration.
2. In your profiles, add this type to `Associable items to a ticket` list. You can do this opening profile form in `Administration > Profiles` and go to the `Assistance` tab.

**Comment by okvok** [comment] 2020-11-19 08:23
It already checked and set.
Unset and set checkboxes don't work.

**Comment by cedric-anne** [comment] 2020-11-19 08:25
> It already checked and set.
> Unset and set checkboxes don't work.

OK. This is not related to current issue, so please open a new one as this one will be closed when fix will be merged.

**Comment by okvok** [comment] 2020-11-19 08:27
I've already fixed it by sql request.
Unfortunately I can't clarify the reason of resetting of filed "is_helpdesk_visible" to 0 was it glpi upgrade or generic object update.

**Closed** 2020-12-14 13:32 UTC
Labels: bug
