### ISSUE TITLE
Change of the database layout - glpi_plugin_genericobject_types (0 seconds)

### ISSUE THREAD

**Issue by Samichio** [pluginsGLPI/genericobject#152] opened 2017-07-27 12:26 UTC
After an messed up GLPI update I reinstalled the plugins, unfortunately I am getting the error
`Change of the database layout - glpi_plugin_genericobject_types (0 seconds)`
when upgrading the genericobject plugin.

Since I thought that the update was complete, forgetting about the plugins, I already deleted the backup of the GLPI folder. As you can see, we added one generic object called "Allgemein". 

MySQL Error Log:
`2017-01-12 13:15:37
*** MySQL query error: 
***
SQL: SELECT *
                         FROM `glpi_profiles` WHERE  (`glpi_profiles`.`interface` = \'helpdesk\')  OR (`glpi_profiles`.`interface` = \'central\'  AND (`glpi_profiles`.`computer` IS NULL
                                   OR `glpi_profiles`.`computer` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`monitor` IS NULL
                                   OR `glpi_profiles`.`monitor` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`software` IS NULL
                                   OR `glpi_profiles`.`software` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`networking` IS NULL
                                   OR `glpi_profiles`.`networking` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`internet` IS NULL
                                   OR `glpi_profiles`.`internet` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`printer` IS NULL
                                   OR `glpi_profiles`.`printer` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`peripheral` IS NULL
                                   OR `glpi_profiles`.`peripheral` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`cartridge` IS NULL
                                   OR `glpi_profiles`.`cartridge` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`consumable` IS NULL
                                   OR `glpi_profiles`.`consumable` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`phone` IS NULL
                                   OR `glpi_profiles`.`phone` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`notes` IS NULL
                                   OR `glpi_profiles`.`notes` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`contact_enterprise` IS NULL
                                   OR `glpi_profiles`.`contact_enterprise` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`document` IS NULL
                                   OR `glpi_profiles`.`document` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`contract` IS NULL
                                   OR `glpi_profiles`.`contract` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`infocom` IS NULL
                                   OR `glpi_profiles`.`infocom` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`knowbase` IS NULL
                                   OR `glpi_profiles`.`knowbase` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`knowbase_admin` IS NULL
                                   OR `glpi_profiles`.`knowbase_admin` IN (\'0\', \'\'))  AND (`glpi_profiles`.`faq` IS NULL
                                   OR `glpi_profiles`.`faq` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`reservation_helpdesk` IS NULL
                                   OR `glpi_profiles`.`reservation_helpdesk` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`reservation_central` IS NULL
                                   OR `glpi_profiles`.`reservation_central` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`reports` IS NULL
                                   OR `glpi_profiles`.`reports` IN (\'r\', \'\'))  AND (`glpi_profiles`.`dropdown` IS NULL
                                   OR `glpi_profiles`.`dropdown` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`entity_dropdown` IS NULL
                                   OR `glpi_profiles`.`entity_dropdown` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`device` IS NULL
                                   OR `glpi_profiles`.`device` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`typedoc` IS NULL
                                   OR `glpi_profiles`.`typedoc` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`link` IS NULL
                                   OR `glpi_profiles`.`link` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`config` IS NULL
                                   OR `glpi_profiles`.`config` IN (\'0\', \'\'))  AND (`glpi_profiles`.`rule_ticket` IS NULL
                                   OR `glpi_profiles`.`rule_ticket` IN (\'0\', \'\'))  AND (`glpi_profiles`.`entity_rule_ticket` IS NULL
                                   OR `glpi_profiles`.`entity_rule_ticket` IN (\'0\', \'\'))  AND (`glpi_profiles`.`rule_import` IS NULL
                                   OR `glpi_profiles`.`rule_import` IN (\'0\', \'\'))  AND (`glpi_profiles`.`rule_ldap` IS NULL
                                   OR `glpi_profiles`.`rule_ldap` IN (\'0\', \'\'))  AND (`glpi_profiles`.`rule_softwarecategories` IS NULL
                                   OR `glpi_profiles`.`rule_softwarecategories` IN (\'0\', \'\'))  AND (`glpi_profiles`.`search_config` IS NULL
                                   OR `glpi_profiles`.`search_config` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`search_config_global` IS NULL
                                   OR `glpi_profiles`.`search_config_global` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`check_update` IS NULL
                                   OR `glpi_profiles`.`check_update` IN (\'r\', \'\'))  AND (`glpi_profiles`.`profile` IS NULL
                                   OR `glpi_profiles`.`profile` IN (\'r\', \'\'))  AND (`glpi_profiles`.`user` IS NULL
                                   OR `glpi_profiles`.`user` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`user_authtype` IS NULL
                                   OR `glpi_profiles`.`user_authtype` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`group` IS NULL
                                   OR `glpi_profiles`.`group` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`entity` IS NULL
                                   OR `glpi_profiles`.`entity` IN (\'0\', \'\'))  AND (`glpi_profiles`.`transfer` IS NULL
                                   OR `glpi_profiles`.`transfer` IN (\'0\', \'\'))  AND (`glpi_profiles`.`logs` IS NULL
                                   OR `glpi_profiles`.`logs` IN (\'0\', \'\'))  AND (`glpi_profiles`.`reminder_public` IS NULL
                                   OR `glpi_profiles`.`reminder_public` IN (\'0\', \'\'))  AND (`glpi_profiles`.`rssfeed_public` IS NULL
                                   OR `glpi_profiles`.`rssfeed_public` IN (\'0\', \'\'))  AND (`glpi_profiles`.`bookmark_public` IS NULL
                                   OR `glpi_profiles`.`bookmark_public` IN (\'0\', \'\'))  AND (`glpi_profiles`.`backup` IS NULL
                                   OR `glpi_profiles`.`backup` IN (\'0\', \'\'))  AND (`glpi_profiles`.`create_ticket` IS NULL
                                   OR `glpi_profiles`.`create_ticket` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`delete_ticket` IS NULL
                                   OR `glpi_profiles`.`delete_ticket` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`add_followups` IS NULL
                                   OR `glpi_profiles`.`add_followups` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`group_add_followups` IS NULL
                                   OR `glpi_profiles`.`group_add_followups` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`global_add_followups` IS NULL
                                   OR `glpi_profiles`.`global_add_followups` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`global_add_tasks` IS NULL
                                   OR `glpi_profiles`.`global_add_tasks` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`update_ticket` IS NULL
                                   OR `glpi_profiles`.`update_ticket` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`update_priority` IS NULL
                                   OR `glpi_profiles`.`update_priority` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`steal_ticket` IS NULL
                                   OR `glpi_profiles`.`steal_ticket` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`assign_ticket` IS NULL
                                   OR `glpi_profiles`.`assign_ticket` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`show_all_ticket` IS NULL
                                   OR `glpi_profiles`.`show_all_ticket` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`show_assign_ticket` IS NULL
                                   OR `glpi_profiles`.`show_assign_ticket` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`show_full_ticket` IS NULL
                                   OR `glpi_profiles`.`show_full_ticket` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`observe_ticket` IS NULL
                                   OR `glpi_profiles`.`observe_ticket` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`update_followups` IS NULL
                                   OR `glpi_profiles`.`update_followups` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`update_tasks` IS NULL
                                   OR `glpi_profiles`.`update_tasks` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`show_planning` IS NULL
                                   OR `glpi_profiles`.`show_planning` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`show_group_planning` IS NULL
                                   OR `glpi_profiles`.`show_group_planning` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`show_all_planning` IS NULL
                                   OR `glpi_profiles`.`show_all_planning` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`statistic` IS NULL
                                   OR `glpi_profiles`.`statistic` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`password_update` IS NULL
                                   OR `glpi_profiles`.`password_update` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`rule_dictionnary_software` IS NULL
                                   OR `glpi_profiles`.`rule_dictionnary_software` IN (\'0\', \'\'))  AND (`glpi_profiles`.`rule_dictionnary_dropdown` IS NULL
                                   OR `glpi_profiles`.`rule_dictionnary_dropdown` IN (\'0\', \'\'))  AND (`glpi_profiles`.`budget` IS NULL
                                   OR `glpi_profiles`.`budget` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`import_externalauth_users` IS NULL
                                   OR `glpi_profiles`.`import_externalauth_users` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`notification` IS NULL
                                   OR `glpi_profiles`.`notification` IN (\'0\', \'\'))  AND (`glpi_profiles`.`rule_mailcollector` IS NULL
                                   OR `glpi_profiles`.`rule_mailcollector` IN (\'0\', \'\'))  AND (`glpi_profiles`.`validate_request` IS NULL
                                   OR `glpi_profiles`.`validate_request` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`create_request_validation` IS NULL
                                   OR `glpi_profiles`.`create_request_validation` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`calendar` IS NULL
                                   OR `glpi_profiles`.`calendar` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`sla` IS NULL
                                   OR `glpi_profiles`.`sla` IN (\'0\', \'\'))  AND (`glpi_profiles`.`rule_dictionnary_printer` IS NULL
                                   OR `glpi_profiles`.`rule_dictionnary_printer` IN (\'0\', \'\'))  AND (`glpi_profiles`.`update_own_followups` IS NULL
                                   OR `glpi_profiles`.`update_own_followups` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`delete_followups` IS NULL
                                   OR `glpi_profiles`.`delete_followups` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`entity_helpdesk` IS NULL
                                   OR `glpi_profiles`.`entity_helpdesk` IN (\'0\', \'\'))  AND (`glpi_profiles`.`show_my_problem` IS NULL
                                   OR `glpi_profiles`.`show_my_problem` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`show_all_problem` IS NULL
                                   OR `glpi_profiles`.`show_all_problem` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`edit_all_problem` IS NULL
                                   OR `glpi_profiles`.`edit_all_problem` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`delete_problem` IS NULL
                                   OR `glpi_profiles`.`delete_problem` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`create_ticket_on_login` IS NULL
                                   OR `glpi_profiles`.`create_ticket_on_login` IN (\'0\', \'\'))  AND (`glpi_profiles`.`tickettemplate` IS NULL
                                   OR `glpi_profiles`.`tickettemplate` IN (\'0\', \'\'))  AND (`glpi_profiles`.`ticketrecurrent` IS NULL
                                   OR `glpi_profiles`.`ticketrecurrent` IN (\'0\', \'\'))  AND (`glpi_profiles`.`ticketcost` IS NULL
                                   OR `glpi_profiles`.`ticketcost` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`validate_incident` IS NULL
                                   OR `glpi_profiles`.`validate_incident` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`create_incident_validation` IS NULL
                                   OR `glpi_profiles`.`create_incident_validation` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`delete_validations` IS NULL
                                   OR `glpi_profiles`.`delete_validations` IN (\'0\', \'1\', \'\'))  AND (`glpi_profiles`.`tickettemplates_id` IS NULL
                                   OR `glpi_profiles`.`tickettemplates_id` IN (\'0\', \'\'))  AND (`glpi_profiles`.`PluginGenericobjectAllgemein` IS NULL
                                   OR `glpi_profiles`.`PluginGenericobjectAllgemein` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`PluginGenericobjectAllgemein_open_ticket` IS NULL
                                   OR `glpi_profiles`.`PluginGenericobjectAllgemein_open_ticket` IN (\'0\', \'\'))  AND (`glpi_profiles`.`PluginGenericobjectActivatedcomponent` IS NULL
                                   OR `glpi_profiles`.`PluginGenericobjectActivatedcomponent` IN (\'w\', \'r\', \'\'))  AND (`glpi_profiles`.`PluginGenericobjectActivatedcomponent_open_ticket` IS NULL
                                   OR `glpi_profiles`.`PluginGenericobjectActivatedcomponent_open_ticket` IN (\'0\', \'\'))  AND (`glpi_profiles`.`profiles_id` IS NULL
                                   OR `glpi_profiles`.`profiles_id` IN (\'0\', \'\')) )
Error: Unknown column 'glpi_profiles.PluginGenericobjectAllgemein' in 'where clause'
Backtrace :
/var/www/html/glpi/inc/profile.class.php&nbsp;:441		DBmysql->query()
/var/www/html/glpi/inc/user.class.php&nbsp;:1597		Profile::currentUserHaveMoreRightThan()
/var/www/html/glpi/inc/user.class.php&nbsp;:1622		User->currentUserHaveMoreRightThan()
/var/www/html/glpi/front/user.form.php&nbsp;:172		User->showForm()
/var/www/html/glpi/front/user.form.php`

I am guessing that some files are missing, now that the plugin folder was basically reset, but not the database.
Any help is appreciated!

**Comment by cedric-anne** [comment] 2018-05-15 09:05
Hi,

Can you try to update to version 2.5.0 of plugin and 9.2.3 of GLPI and check if this problem is still present ?

Thanks

**Comment by cedric-anne** [comment] 2018-06-05 07:42
Hi,

As I cannot reproduce this issue, I close it.

Regards

**Closed by cedric-anne** 2018-06-05 07:42 UTC
Labels: need feedback
