### ISSUE TITLE
Differences and error between 2 views in GLPI

### ISSUE THREAD

**Issue by chauchse** [pluginsGLPI/genericobject#228] opened 2018-10-27 10:39 UTC
Hello,

I use the great plugin genericobject.
I have on several tickets a lot of genericobject linked. 
When i search a ticket in the front/ticket.php view of glpi, i have mistakes in the results
[https://imgur.com/SPk0aqy](url)

As you can see in the linked picture, there is a linked element named "JALFICH"
When i open the ticket. This element JALFISH is not present in the ticket.

`
X3action : 12	Entity                  ZAGREGEINV	-	-
 
Entity                  ZCPLCTLINV	-	-
 
Entity                  ZINVTMP	-	-
 
Entity                  ZINVTMPIN	-	-
 
Entity                  ZMODIFINV	-	-
 
Entity                  ZSAINVCTRL	-	-
 
Entity                  ZSELARTINC	-	-
 
Entity                  ZSELARTINV	-	-
 
Entity                  ZSELCUN	-	-
 
Entity                  ZSELOCINC	-	-
 
Entity                  ZSELOCINV	-	-
 
Entity                  ZSELOCINVM	-	-
 
X3ecran : 5	Entity                  ZINVAGREGE	-	-
 
Entity                  ZINVCTRL	-	-
 
Entity                  ZINVMODIF	-	-
 
Entity                  ZINVTMP	-	-
 
Entity                  ZINVTMPIN	-	-
 
X3fenetre : 5	Entity                  OZINVAGREGE	-	-
 
Entity                  OZINVCTRL	-	-
 
Entity                  OZINVMODIF	-	-
 
Entity                  OZINVTMP	-	-
 
Entity                  OZINVTMPIN	-	-
 
X3fonction : 5	Entity                  GESZCPLCTL	-	-
 
Entity                  GESZINVAGR	-	-
 
Entity                  GESZINVINC	-	-
 
Entity                  GESZINVMOD	-	-
 
Entity                  GESZINVTMP	-	-
 
X3importexport : 2	Entity                  ZINV01100	-	-
 
Entity                  ZINV01101	-	-
 
X3table : 8	Entity                  ZINVAGREGERR	-	-
 
Entity                  STOLOC [STC]	-	-
 
Entity                  XGALTRA [XGT]	-	-
 
Entity                  ZINVAGREGE	-	-
 
Entity                  ZINVTMP	-	-
 
Entity                  ZINVTMPERR	-	-
 
Entity                  ZUCMOVEX	-	-
 
Entity                  ZWINVAGRERR	-	-
 
X3traitement : 15	Entity                  CLGRIS.SPEZINVMODIF	-	-
 
Entity                  CLGRIS.SPEZINVTMP	-	-
 
Entity                  CLGRIS.SPEZINVTMPIN	-	-
 
Entity                  CLGRIS.SPEZIVM	-	-
 
Entity                  CLGRIS.SPEZIVN	-	-
 
Entity                  CLGRIS.SPEZIVT	-	-
 
Entity                  CLGRIS.SPEZSAINVAGR	-	-
 
Entity                  CLGRIS.SPEZSAINVCTRL	-	-
 
Entity                  CLGRIS.SPEZSELARTINC	-	-
 
Entity                  CLGRIS.SPEZSELARTINV	-	-
 
Entity                  CLGRIS.SPEZSELCUN	-	-
 
Entity                  CLGRIS.SPEZSELOCINC	-	-
 
Entity                  CLGRIS.SPEZSELOCINV	-	-
 
Entity                  CLGRIS.SPEZSELOCINVM	-	-
 
Entity                  SPEZCPLCTLINV	-	-
 
X3vue	Entity                  ZVINVART	X3action : 12	Entity                  ZAGREGEINV	-	-
 
Entity                  ZCPLCTLINV	-	-
 
Entity                  ZINVTMP	-	-
 
Entity                  ZINVTMPIN	-	-
 
Entity                  ZMODIFINV	-	-
 
Entity                  ZSAINVCTRL	-	-
 
Entity                  ZSELARTINC	-	-
 
Entity                  ZSELARTINV	-	-
 
Entity                  ZSELCUN	-	-
 
Entity                  ZSELOCINC	-	-
 
Entity                  ZSELOCINV	-	-
 
Entity                  ZSELOCINVM	-	-
 
X3ecran : 5	Entity                  ZINVAGREGE	-	-
 
Entity                  ZINVCTRL	-	-
 
Entity                  ZINVMODIF	-	-
 
Entity                  ZINVTMP	-	-
 
Entity                  ZINVTMPIN	-	-
 
X3fenetre : 5	Entity                  OZINVAGREGE	-	-
 
Entity                  OZINVCTRL	-	-
 
Entity                  OZINVMODIF	-	-
 
Entity                  OZINVTMP	-	-
 
Entity                  OZINVTMPIN	-	-
 
X3fonction : 5	Entity                  GESZCPLCTL	-	-
 
Entity                  GESZINVAGR	-	-
 
Entity                  GESZINVINC	-	-
 
Entity                  GESZINVMOD	-	-
 
Entity                  GESZINVTMP	-	-
 
X3importexport : 2	Entity                  ZINV01100	-	-
 
Entity                  ZINV01101	-	-
 
X3table : 8	Entity                  ZINVAGREGERR	-	-
 
Entity                  STOLOC [STC]	-	-
 
Entity                  XGALTRA [XGT]	-	-
 
Entity                  ZINVAGREGE	-	-
 
Entity                  ZINVTMP	-	-
 
Entity                  ZINVTMPERR	-	-
 
Entity                  ZUCMOVEX	-	-
 
Entity                  ZWINVAGRERR	-	-
 
X3traitement : 15	Entity                  CLGRIS.SPEZINVMODIF	-	-
 
Entity                  CLGRIS.SPEZINVTMP	-	-
 
Entity                  CLGRIS.SPEZINVTMPIN	-	-
 
Entity                  CLGRIS.SPEZIVM	-	-
 
Entity                  CLGRIS.SPEZIVN	-	-
 
Entity                  CLGRIS.SPEZIVT	-	-
 
Entity                  CLGRIS.SPEZSAINVAGR	-	-
 
Entity                  CLGRIS.SPEZSAINVCTRL	-	-
 
Entity                  CLGRIS.SPEZSELARTINC	-	-
 
Entity                  CLGRIS.SPEZSELARTINV	-	-
 
Entity                  CLGRIS.SPEZSELCUN	-	-
 
Entity                  CLGRIS.SPEZSELOCINC	-	-
 
Entity                  CLGRIS.SPEZSELOCINV	-	-
 
Entity                  CLGRIS.SPEZSELOCINVM	-	-
 
Entity                  SPEZCPLCTLINV	-	-
 
X3vue	Entity                  ZVINVART	
`

Could you help me ?

**Comment by stonebuzz** [comment] 2020-01-24 11:06
This issue hasn’t evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

**Closed by stonebuzz** 2020-01-24 11:06 UTC
