### ISSUE TITLE
Update GLPI

### ISSUE THREAD

**Issue by PawelGit** [pluginsGLPI/genericobject#126] opened 2017-02-18 12:59 UTC
Hi!
I updated version of glpi from 0.84.8 to 9.1.1 and plugin objects management from 2.3.2  to 2.4.0.
I can't now add records to the objects defined by the plugin(no button add in assets).
I can add new records but after create new object. How can I fix it?

**Comment by stonebuzz** [comment] 2020-01-27 08:50
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-27 08:50 UTC
