### ISSUE TITLE
Internationalization of object name (/ Object name Truncation / change and no editing of names)

### ISSUE THREAD

**Issue by vrdriver** [pluginsGLPI/genericobject#106] opened 2016-08-31 06:01 UTC
Hi,
I tried creating a new object, and called it "UPS", as in, Uninterruptible Power Supply, however after entering UPS, and checking it was correct, I hit save, (I did this twice to confirm) then entry saved as "up". 

I discovered by running "SELECT \* FROM ucb_glpi.glpi_plugin_genericobject_types;" that indeed this was true, and that "up" was stored in the field "name".

I changed it to the correct name, and it is now showing "ups". I couldn't be bothered with symantics of uppercase stuff, but there appears to be an issue of some sort. 

Firefox Dev Ed: 50.0a2 (2016-08-29)
Using Version: 0.85-1.0 for GLPi 0.85 & 0.90

Also, another side note, there currently seems to be no official way to edit the objects once they are created. ?

**Comment by btry** [comment] 2016-08-31 07:10
Hi

GLPi has some naming conventions about the database tables. For example, table names use plural. 

The features provided by this plugin makes it needs to manage plurals as well as GLPi. The plural is computed using the rules of english langiage. I'm afraid UPS is not recognizable by the related code because it is more an acronym than a real word (or group of words).

I think it is not a bug. This is more likely a problem related to your usage of the plugin. 

You should use *uninterruptible power supply* instead of *UPS*. This way the code in charge of computation of plural should just work.

I add question label on this ticket : maybe making the plugin should fail creating an object if it cannot compute the plural. This should avoid the truncation you observed.

**Comment by vrdriver** [comment] 2016-08-31 07:36
Ah, ok, well that explains the problem I was having well. Thanks for that. Appreciate it. 
I do find it strange that it does have the plural filtering, but, as it's a multilingual system... then maybe. haha
Cheers.
-Steve

**Comment by vrdriver** [comment] 2016-08-31 07:52
Actually, I've been thinking about this, and working more with it... This plugin strips the spaces in the fields.
So, "lightning arrester bnc" becomes "lightningarresterbnc".
I understand that for the actual table name, but for the label name, it should still include the spaces in the entry and not strip them.

**Comment by btry** [comment] 2016-08-31 08:19
To do a summary : 
- truncation of the name is (probably) related to the "plural engine" and the use of acronyms. Acronyms are not recommended

- rename of an object is complex : it needs changes on generated files, and this is harder than creating them from their templates. It also needs to rename a table. If the name contains an error, it may be detected by the user after creation and before adding data. Destroying the object and creating a new one is sufficient. (but contributions are welcome is someone really wants this)

- Internationalization of the name needs investigation. it might require some additional compelxity to the plugin. I'll update the ticket after a review of the code about this feature.

**Comment by vrdriver** [comment] 2017-10-20 03:56
Hi @btry, I was just wondering where this is currently sitting in the priority list as it's been over a year?

**Comment by btry** [comment] 2017-10-20 08:22
For now this is a community issue, and it has a low impact. 

Community support is done at best effort, and I must admit that I'm very busy with an other plugin since 2016. I'm sorry about that.

If you require enhancements related to this issue and you're ready to sponsor them then contact us at contact@teclib.com.

**Comment by vrdriver** [comment] 2017-10-20 08:34
No dramas. I totally understand having other projects. Thanks for the quick update.

**Comment by stonebuzz** [comment] 2020-01-27 08:52
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards

**Closed by stonebuzz** 2020-01-27 08:52 UTC
Labels: enhancement, question
