### ISSUE TITLE
 Invalid default value for 'date_mod'

### ISSUE THREAD

**Issue by samwank** [pluginsGLPI/genericobject#68] opened 2015-12-03 07:56 UTC
when i try to install i get an error message to the effect that : Work in progress...
Invalid default value for 'date_mod'

**Comment by samwank** [comment] 2015-12-03 07:57
sorry i get error msg:


Work in progress...
Invalid default value for 'date_mod'

**Comment by btry** [comment] 2015-12-03 08:03
Hi, 

There is very likely more details in glpi/files/_log/sql-errors.log about this error. Can you provide them ?

**Comment by samwank** [comment] 2015-12-03 08:09
hello , 
[sql-errors.log.pdf](https://github.com/TECLIB/genericobject/files/50561/sql-errors.log.pdf)

**Comment by btry** [comment] 2015-12-03 08:32
I tested manually the query, and it works for me. I think the issue is related to your database engine.
On which operating system is running your GLPI, especially your database ?
Which database engine are you using (mysql, mariadb), and which version ?

**Comment by samwank** [comment] 2015-12-03 09:26
hello i am using mysql on windows 7 development laptop

**Comment by btry** [comment] 2015-12-03 09:31
Ok, and which is the DBMS ?

**Comment by samwank** [comment] 2015-12-03 09:35
the DBMS is mySQL

**Comment by btry** [comment] 2015-12-03 09:38
have a look on this  : 

http://stackoverflow.com/questions/25349126/how-can-i-set-the-default-value-of-a-field-as-0000-00-00-000000

https://dev.mysql.com/doc/refman/5.5/en/sql-mode.html

Maybe you're using a specific setting disallowing a date made of zeroes.

**Comment by samwank** [comment] 2015-12-03 10:45
Hi thanx . that link helped . i changed the default value to 1000-01-01 00:00:0 in C:\wamp\www\ICTinventory\plugins\genericobject\inc\type.class.php line 1800 and am good

**Comment by btry** [comment] 2015-12-03 12:24
Actually, I was expecting you check the settings of your DBMS. 

SELECT @@GLOBAL.sql_mode global, @@SESSION.sql_mode session

to see if you have a specific setting. 

The DBMS I used to check the query returns 
global = NO_ENGINE_SUBSTITUTION
session = NO_ENGINE_SUBSTITUTION

Patching as you did exposes you to probable bug un the future, which may be hard to find because the table definition is probably the last place someone will search for a bug.

I recommend you to avoid patching the code someway that will never be put in mainstream development, if a better solution exists.

If you still want to use the patch you did, You're welcome to close the ticket.

**Comment by samwank** [comment] 2015-12-03 12:45
i am getting :
global:    STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERR
session: STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERR...

**Comment by btry** [comment] 2015-12-03 13:00
Ok, then use the 2nd link I gave you earlier (mysql documentation) to correctly set your DBMS.

Choose the same version of the page as your DBMS.

The exact query depends on what you want to drop among the active options.

to match the same as I showed :
SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION'; 
SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION'; 

stop and restart mysql to ensure the new settings are saved and active, and check if you may install  the plugin without your change.

**Comment by samwank** [comment] 2015-12-03 13:13
just tried , didn't work. will explore further tomorrow

**Comment by dethegeek** [comment] 2016-01-18 20:02
Hi

I think I found a fix for the plugin. I guess you're using GLPI 0.90+ .

Can you try this version of the plugin and feedback ?

https://github.com/TECLIB/genericobject/archive/sql-strict.zip

**Comment by Kjatox** [comment] 2016-03-01 09:15
Hello,
Same message: traitement en cours
Error:
PHP Fatal error:  Class 'PluginGenericobjectFrfrfr' not found in C:\\wamp\\www\\glpi\\plugins\\genericobject\\inc\\type.class.php on line 1822, referer: http://192.168.0.203:8080/glpi/front/plugin.php
PHP Stack trace:, referer: http://192.168.0.203:8080/glpi/front/plugin.php
PHP   1. {main}() C:\\wamp\\www\\glpi\\front\\plugin.form.php:0, referer: http://192.168.0.203:8080/glpi/front/plugin.php
PHP   2. call_user_func() C:\\wamp\\www\\glpi\\front\\plugin.form.php:49, referer: http://192.168.0.203:8080/glpi/front/plugin.php
PHP   3. Plugin->install() C:\\wamp\\www\\glpi\\front\\plugin.form.php:49, referer: http://192.168.0.203:8080/glpi/front/plugin.php
PHP   4. plugin_genericobject_install() C:\\wamp\\www\\glpi\\inc\\plugin.class.php:643, referer: http://192.168.0.203:8080/glpi/front/plugin.php
PHP   5. PluginGenericobjectType::install() C:\\wamp\\www\\glpi\\plugins\\genericobject\\hook.php:118, referer: http://192.168.0.203:8080/glpi/front/plugin.php

Try with sql-strict but same problem

Version: GLPI 0.90.1

**Comment by trasher** [comment] 2017-03-20 10:48
I guess the fix proposed in commit https://github.com/pluginsGLPI/genericobject/commit/4af94349321fb6982c53cae1c60a79ba92e1377e is OK; i'll add it for the next release.

**Comment by trasher** [comment] 2017-03-20 10:54
In facts, this has already been fixed in 62ec5713a9b1dee758155d4570164c3ff79b797f

**Closed by trasher** 2017-03-20 10:54 UTC
