### ISSUE TITLE
change tab disappears when plugin is activated

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/genericobject#137] opened 2017-05-29 11:18 UTC
Hello

When I activate the plugin change tab disappears in ticket and ticket tab disappears in change

**Comment by stonebuzz** [comment] 2020-01-27 08:50
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-27 08:50 UTC
