### ISSUE TITLE
Generic Object menu hides

### ISSUE THREAD

**Issue by Benchohra** [pluginsGLPI/genericobject#184] opened 2018-04-19 10:41 UTC
Hello,
after creating a generic object and activating , i started the creation of items, every thing seems to be good, but whene updating an item the generic object menu hide and i cant create more items so i have to disconnect and connect againt to create new items.
scenario :
1-Create generic object and activate
2-create item for the generic object and save
3-edit the item and update

glpi version : 9.2.1
generic object version : 2.5.0

![gen obj 1](https://user-images.githubusercontent.com/37929171/38987016-4b18f288-43c6-11e8-9463-c41867c980ea.jpg)
![gen obj 2](https://user-images.githubusercontent.com/37929171/38987019-4b4f5b52-43c6-11e8-9b12-fa2334771d93.jpg)
![gen obj 3](https://user-images.githubusercontent.com/37929171/38987020-4b7b50f4-43c6-11e8-8798-9366b8511321.jpg)
![gen obj 4](https://user-images.githubusercontent.com/37929171/38987021-4ba3cdb8-43c6-11e8-923c-da0be2701a02.jpg)

**Comment by cedric-anne** [comment] 2018-05-14 11:41
Hello,

I tried on GLPI 9.2.3 and I cannot reproduce this issue. Can you try to update to GLPI 9.2.3 and check if you still have this problem ?

Thanks

**Comment by cedric-anne** [comment] 2018-06-05 13:39
Hi,

As I cannot reproduce this issue, I close it.

Regards

**Closed by cedric-anne** 2018-06-05 13:39 UTC
Labels: bug, need feedback
