### ISSUE TITLE
[feature]Volumes/Components

### ISSUE THREAD

**Issue by dsever** [pluginsGLPI/genericobject#165] opened 2017-12-13 15:28 UTC
Hi, 

Is is possible to create genericObject that includes other types like Components/Volumes, same as you includes Network using "Use Network connections"?

Thanks
Dubravko

**Comment by stonebuzz** [comment] 2020-01-27 08:50
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-27 08:50 UTC
Labels: enhancement
