### ISSUE TITLE
display empty menu

### ISSUE THREAD

**Issue by yllen** [pluginsGLPI/genericobject#141] opened 2017-07-02 17:49 UTC
I have to create an object but not read it, Asset menu is displayed empty.

**Comment by stonebuzz** [comment] 2020-01-27 08:50
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-27 08:50 UTC
