### ISSUE TITLE
search is broken inside object generated by genericobjects in 0.85.5

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [pluginsGLPI/genericobject#133] opened 2017-04-27 13:45 UTC
Hello,

when objects generated by generic objects are listed clicking on the arrow to get to the next page we get this error

> PHP Notice: Undefined index: PluginGenericobjectLogistique?sort=1 in /var/www/glpi/inc/search.class.php at line 5252
> PHP Warning: Invalid argument supplied for foreach() in /var/www/glpi/inc/search.class.php at line 5252
> +    
> PHP Warning: reset() expects parameter 1 to be array, null given in /var/www/glpi/ajax/searchrow.php at line 147
> PHP Warning: Invalid argument supplied for foreach() in /var/www/glpi/ajax/searchrow.php at line 150
> 	
> PHP Warning: Invalid argument supplied for foreach() in /var/www/glpi/inc/search.class.php at line 5252
> 	
> 	
> Enregistrer comme marque-page  Raz
> PHP Warning: Invalid argument supplied for foreach() in /var/www/glpi/inc/search.class.php at line 5252
> PHP Warning: Invalid argument supplied for foreach() in /var/www/glpi/inc/search.class.php at line 5252
> 
> Fatal error: Call to a member function isEntityAssign() on a non-object in /var/www/glpi/inc/search.class.php on line 319

glpi is version 0.85.5 and generic object 2.4.0

Cheers

**Comment by loicbenoit** [comment] 2018-08-24 17:52
Could provide more info on how to reproduce the issue or even screenshots?

### Step to reproduce (what I did):
1. On the index page of one of my GenericObject, search for a letter commonly found in the name of an object (just to get enough results for paging to quick-in). Any search with enough results will do.
2. Click on the paging arrow to get to the next result page.

### Expected result:
When clicking on "next result page" and "previous result page", the corresponding result listing page is shown.

### Actual result:
Exactly as expected.

Please begin by updating GLPI and your plugins. If the problem still persists, please help us understand how to reproduce the issue.

**Comment by stonebuzz** [comment] 2020-01-27 08:50
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-27 08:50 UTC
Labels: bug
