### ISSUE TITLE
rework autoloader

### ISSUE THREAD

**Issue by orthagh** [pluginsGLPI/genericobject#128] opened 2017-02-27 15:48 UTC
see glpi-project/glpi#1855

we need to include (or drop) Zend\Loader\SplAutoloader

**Comment by stonebuzz** [comment] 2020-01-27 08:50
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-27 08:50 UTC
