### ISSUE TITLE
Issue : enable to add an assigned tech from a ticket[9.2/2.4.0]

### ISSUE THREAD

**Issue by anlifr** [pluginsGLPI/genericobject#159] opened 2017-11-07 16:31 UTC
Hi,

 I can't assign tickets to a technician with this plugin.
When i add a technician,there is a refresh with no error but the user don't appear.

I tried [this fix ](https://github.com/pluginsGLPI/genericobject/issues/153) but not work.

Thanks .

**Comment by stonebuzz** [comment] 2020-01-27 08:50
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-27 08:50 UTC
