### ISSUE TITLE
Add a dropdown field points to another Generic Object

### ISSUE THREAD

**Issue by mahkorayem** [pluginsGLPI/genericobject#135] opened 2017-05-09 18:29 UTC
Can I add a field like users in core to provide a dropdown with names from another Generic Object

Or connect like the one in the Computer

**Comment by kevinforrestconnors** [comment] 2019-07-08 16:11
It blows my mind that this is not implemented.  There's even an open PR from 2016 that never got merged?

Is there another way to link objects together or do most people just not want to have relations between their objects??

**Comment by stonebuzz** [comment] 2020-01-27 08:50
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-27 08:50 UTC
