### ISSUE TITLE
Checking global search add useless fields

### ISSUE THREAD

**Issue by neeftarah** [pluginsGLPI/genericobject#64] opened 2015-11-20 09:50 UTC
Hi,

In the current version, when we check the "use global research" option, several fields are automatically added with no reason and can't be removed. (serial, otherserial, location, status, user, group, manufacturer, Technician in charge of the hardware).
They should not.

**Comment by wawax** [comment] 2015-11-20 09:54
Yes it must stay.
It's for global search

**Comment by loicbenoit** [comment] 2018-08-24 17:58
If these fields are required for global search, this is not a bug, but an request for enhancement.

It appears that you want to be able to hide mandatory fields that you don't want to use. It doesn't really matter if they are present in the DB, as long as you can choose to hide them in the GUI.

Seing as this ticket is very old, probably solved and quite stale, who is responsible for closing it if the original author never follows through?

**Comment by stonebuzz** [comment] 2020-01-27 08:53
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards

**Closed by stonebuzz** 2020-01-27 08:53 UTC
Labels: bug
