### ISSUE TITLE
GenericObject classes not autoloding in /front/comments.php

### ISSUE THREAD

**Issue by loicbenoit** [pluginsGLPI/genericobject#216] opened 2018-09-13 15:32 UTC
### Steps to reproduce
1- Add a custom dropdown to a GenericObject. My dropdown was global, but it shouldn't matter.
2- Go to objet preview OR create a new object instance and view it's main form.
3- Select a value in the dropdown.
4- Hover the mouse cursor over the "i".

### Expected result
Script "glpi/front/comments.php" is able to load the class associated to my custom object in order to display the usual content in the info popup.

### Current result
Script "glpi/front/comments.php" displays a PHP error.

### The problem to solve
PHP errors stem from bugs in GLPI core files, which you don't have to address here. I'll open tickets for those in the main GLPI project.

The problem that concerns GenericObject is that "glpi/front/comments.php" doesn't load the GenericObject autoloder. Thus, even after solving all the other bugs in GLPI's core, it still can't load the class for my custom object, even do it correctly identifies the table name and the class name.

Because the GLPI project doesn't officially support plugins nor custom objects, we have to find a solution here.

This is a minor bug for plugin GenericObject. Once GLPI's core bugs are resolved, we just get a blank popup instead of the usual popup with details about the dropdown selection.

**Comment by cedric-anne** [comment] 2018-09-17 09:28
Hi,

I cannot reproduce. What do you mean by "custom dropdown" ? Is this related to some other plugin ?

Regards

**Comment by loicbenoit** [comment] 2018-09-17 12:38
Hi,

By custom global dropdown, I mean: https://glpi-plugins.readthedocs.io/en/latest/genericobject/index.html#add-a-global-dropdown

I'm using GenericObject, version 2.6.2, [develop](https://github.com/pluginsGLPI/genericobject/tree/develop)

**Comment by loicbenoit** [comment] 2018-09-17 12:50
Also, I got the file path wrong, it's glpi/htdocs/**ajax**/comments.php

**Comment by loicbenoit** [comment] 2018-09-17 13:32
The bug only happens after you have selected a value in a dropdown that fetches data from a data source created by GenericObject. GenericObject properly creates data tables and PHP classes. The issue is that glpi/htdocs/ajax/comments.php can only use classes autoload by GLPI. Therefore, PHP classes created by plugins such as GenericObject are not autoloaded when that ajax script runs.


### Here is a screenshot of the issue, BEFORE applying fixes to GLPI's core:
![2018-09-17_8-46-39](https://user-images.githubusercontent.com/6154667/45624045-21fdc380-ba57-11e8-91e2-498b0cc35a87.png)


### Here is a screenshot of the issue, AFTER applying fixes to GLPI's core:
![2018-09-17_9-25-56_afert-fixes](https://user-images.githubusercontent.com/6154667/45625782-bcf89c80-ba5b-11e8-9b62-ea20d4853b7b.png)


### Here is the debug info I've used to diagnose the issue:

[2018-09-17 06:05:44] glpiphplog.DEBUG: 
 in /opt/bitnami/apps/glpi/htdocs/ajax/comments.php line 42
POST: 
array (
  'value' => '1',
  'table' => 'glpi_plugin_genericobject_foonoentities',
  'withlink' => 'comment_link_plugin_genericobject_foonoentities_id576661075',
)  {"user":"2@debian"} 

[2018-09-17 06:05:44] glpiphplog.DEBUG: 
with test setup:
1- In dropdown.class.php[288], return if getItemForItemtype(getItemTypeForTable($table)) doesn't produce an object. 
2- The call to spl_autoload_functions() just after:
     $tmpname = Dropdown::getDropdownName($_POST["table"], $_POST["value"], 1);

in /opt/bitnami/apps/glpi/htdocs/ajax/comments.php line 73
spl_autoload_functions: 
array (
  0 => 'glpi_autoload',
  1 => 
  array (
    0 => 
    Composer\Autoload\ClassLoader::__set_state(array(
       'prefixLengthsPsr4' => 
      array (
      ...
      ),
       'classMapAuthoritative' => false,
       '**missingClasses**' => 
      array (
        **'PluginGenericobjectFoonoentity' => true,
        'GlpiPlugin\\Genericobject\\Foonoentity' => true,**
        'UNKNOWN' => true,
      ),
       'apcuPrefix' => NULL,
    )),
    1 => 'loadClass',
  ),
)  {"user":"2@debian","mem_usage":"0.004\", 5.16Mio)"} 


### Proof that PluginGenericobjectFoonoentity exists and is usable
The dropdown is correctly populated with data from PluginGenericobjectFoonoentity. I can select a value and save it in my object.
![2018-09-17_9-21-13_selected](https://user-images.githubusercontent.com/6154667/45625524-10b6b600-ba5b-11e8-9bae-94f672018d9a.png)

**Comment by loicbenoit** [comment] 2018-09-17 13:44
### System info, setup and config
GLPI 9.3.0 (/glpi => /opt/bitnami/apps/glpi/htdocs)
Installation mode: TARBALL

### Server:
Operating system: Linux debian 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
PHP 7.1.18 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,	date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt, mongodb, mysqli, mysqlnd, openssl, pcntl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, soap, sockets, sqlite3, standard, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="128M" post_max_size="40M" safe_mode="" session.save_handler="files" upload_max_filesize="40M" 
Software: Apache ()	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.22
	Server SQL Mode: 
	Parameters: root@localhost/glpi3dev
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
xmlrpc extension is installed
APCu extension is not present
CAS extension is not present
Database version seems correct (5.7.22) - Perfect!Database version seems correct (5.7.22) - Perfect!
OK/opt/bitnami/apps/glpi/htdocs/config : OK
OK/opt/bitnami/apps/glpi/htdocs/files : OK
OK/opt/bitnami/apps/glpi/htdocs/files/_dumps : OK
OK/opt/bitnami/apps/glpi/htdocs/files/_sessions : OK
OK/opt/bitnami/apps/glpi/htdocs/files/_cron : OK
OK/opt/bitnami/apps/glpi/htdocs/files/_graphs : OK
OK/opt/bitnami/apps/glpi/htdocs/files/_lock : OK
OK/opt/bitnami/apps/glpi/htdocs/files/_plugins : OK
OK/opt/bitnami/apps/glpi/htdocs/files/_tmp : OK
OK/opt/bitnami/apps/glpi/htdocs/files/_cache : OK
OK/opt/bitnami/apps/glpi/htdocs/files/_rss : OK
OK/opt/bitnami/apps/glpi/htdocs/files/_uploads : OK
OK/opt/bitnami/apps/glpi/htdocs/files/_pictures : OK
OK/opt/bitnami/apps/glpi/htdocs/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

### Libraries
htmLawed version 1.2.4 in (/opt/bitnami/apps/glpi/htdocs/lib/htmlawed)
SimplePie version 1.5.1 in (/opt/bitnami/apps/glpi/htdocs/vendor/simplepie/simplepie/library)
TCPDF version 6.2.17 in (/opt/bitnami/apps/glpi/htdocs/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/opt/bitnami/apps/glpi/htdocs/vendor/michelf/php-markdown/Michelf)
true/punycode in (/opt/bitnami/apps/glpi/htdocs/vendor/true/punycode/src)
iacaml/autolink in (/opt/bitnami/apps/glpi/htdocs/vendor/iamcal/lib_autolink)
sabre/vobject in (/opt/bitnami/apps/glpi/htdocs/vendor/sabre/vobject/lib)

### SQL replicas
Not active

### Notifications
Way of sending emails: PHP

### Mails receivers

### Plugins list
	fields               Name: Additionnal fields             Version: 1.8.2      State: Enabled
	barcode              Name: Barcode                        Version: 2.2.0      State: Enabled
	etl                  Name: ETL                            Version: 0.0.1      State: Enabled
	datainjection        Name: File injection                 Version: 2.6.3      State: Enabled
	order                Name: Gestion des commandes          Version: 2.2.0      State: Enabled
	genericobject        Name: Objects management             Version: 2.6.2      State: Enabled
	reports              Name: Rapports                       Version: 1.11.3     State: Enabled

**Comment by loicbenoit** [comment] 2018-09-18 18:50
If the dropdown already has a value, you may have change it in order to observe the bug. Then, you'll get the bug even if you reselect the original value.

**Comment by cedric-anne** [comment] 2018-09-20 10:41
Hi,

Plugins are not loaded from ajax files. I made a PR to fix it on glpi core but for future major release, as it is a big change (it is hard to evaluate impacts): https://github.com/glpi-project/glpi/pull/4674.

A second problem is that if Plugin is correctly loaded, link to item form (using the "i" button beside the dropdown) will be invalid. This second PR fixes it: https://github.com/glpi-project/glpi/pull/4675. Also made on master for now.

Regards

**Comment by loicbenoit** [comment] 2018-09-20 15:27
Thanks.

**Closed** 2019-05-30 19:57 UTC
