### ISSUE TITLE
Right for types

### ISSUE THREAD

**Issue by yllen** [pluginsGLPI/genericobject#139] opened 2017-07-02 16:08 UTC
You have a user with many profile: 1 to see types (profile A), 1 with no rights for types (profile B).
In profile A, you open Setup > Genericobject to see list of types.
List of types is displayed.
You change profile to profile B => you can see list of types. When you click on one you are redirect to home page.

Don't display if no rights on types in the profile

**Comment by stonebuzz** [comment] 2020-01-27 08:50
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-27 08:50 UTC
