### ISSUE TITLE
How to upgrade this plugin? 

### ISSUE THREAD

**Issue by geekson** [pluginsGLPI/genericobject#113] opened 2016-11-03 09:23 UTC
Hello,

Is there a procedure to upgrade from 0.90 to 9.1 without losing objects?

Regards,
David

**Comment by trasher** [comment] 2016-11-03 09:35
This should be the default; did you have issues upgrading?

Of course, when you want to upgrade; make sure to backup your database and (for this plugin specifically) plugin files.

**Comment by geekson** [comment] 2016-11-03 09:40
Nope, just want to be sure. To sump up
I just disable the plugin? 
No need to move any files to glpi\plugins\genericobject ?

**Comment by geekson** [comment] 2016-11-03 10:11
I just did the upgrade and I get an upgrade button from the plugin page. When I click I get :+1: Change of the database layout - glpi_plugin_genericobject_types (1 second) and nothing happens.

**Comment by btry** [comment] 2016-11-03 10:14
Hi

Then there is a failure in the upgrade process. Check the following files 
- glpi/files/_log/php-errors.log
- glpi/files/_log/sql-errors.log
- /var/log/apache2/error.log (or equivalent file depending on your setup)

**Comment by geekson** [comment] 2016-11-03 10:21
I only get warning from my upgrade which are :

2016-11-03 11:06:09 [@SPOOL-FR100100V]
glpi_objectlocks table already exists. A backup have been done to backup_glpi_objectlocks. @ 2016-11-03 11:06:09 [@SPOOL-FR100100V]
glpi_networkportfiberchannels table already exists. A backup have been done to backup_glpi_networkportfiberchannels. @ 2016-11-03 11:06:09 [@SPOOL-FR100100V]
glpi_operatingsystemarchitectures table already exists. A backup have been done to backup_glpi_operatingsystemarchitectures. @ 2016-11-03 11:06:09 [@SPOOL-FR100100V]
glpi_tasktemplates table already exists. A backup have been done to backup_glpi_tasktemplates. @ 2016-11-03 11:06:09 [@SPOOL-FR100100V]
glpi_budgettypes table already exists. A backup have been done to backup_glpi_budgettypes. @ 2016-11-03 11:06:09 [@SPOOL-FR100100V]
glpi_apiclients table already exists. A backup have been done to backup_glpi_apiclients. @ 2016-11-03 11:06:10 [@SPOOL-FR100100V]
glpi_computerantiviruses table already exists. A backup have been done to backup_glpi_computerantiviruses. @ 2016-11-03 11:06:10 [@SPOOL-FR100100V]
glpi_slts table already exists. A backup have been done to backup_glpi_slts. @ 2016-11-03 11:06:10 [@SPOOL-FR100100V]
You can delete backup tables if you have no need of them. @ 

my php-errors tells me about my mailgate erros nothing related to generic objects...

**Comment by btry** [comment] 2016-11-03 10:26
There is nothing in the http server's log ? I think you get an error 500.

**Comment by geekson** [comment] 2016-11-03 10:27
[03-Nov-2016 11:22:47 Europe/Paris] PHP Stack trace:

[03-Nov-2016 11:22:47 Europe/Paris] PHP   1. {main}() C:\wamp\www\glpi\front\plugin.form.php:0

[03-Nov-2016 11:22:47 Europe/Paris] PHP   2. call_user_func:{C:\wamp\www\glpi\front\plugin.form.php:49}() C:\wamp\www\glpi\front\plugin.form.php:49

[03-Nov-2016 11:22:47 Europe/Paris] PHP   3. Plugin->install() C:\wamp\www\glpi\front\plugin.form.php:49

[03-Nov-2016 11:22:47 Europe/Paris] PHP   4. plugin_genericobject_install() C:\wamp\www\glpi\inc\plugin.class.php:664

[03-Nov-2016 11:22:47 Europe/Paris] PHP   5. PluginGenericobjectType::install() C:\wamp\www\glpi\plugins\genericobject\hook.php:117

[03-Nov-2016 11:24:57 Europe/Paris] PHP Fatal error:  Class 'PluginGenericobjectBook' not found in C:\wamp\www\glpi\plugins\genericobject\inc\type.class.php on line 1931

[03-Nov-2016 11:24:57 Europe/Paris] PHP Stack trace:

[03-Nov-2016 11:24:57 Europe/Paris] PHP   1. {main}() C:\wamp\www\glpi\front\plugin.form.php:0

[03-Nov-2016 11:24:57 Europe/Paris] PHP   2. call_user_func:{C:\wamp\www\glpi\front\plugin.form.php:49}() C:\wamp\www\glpi\front\plugin.form.php:49

[03-Nov-2016 11:24:57 Europe/Paris] PHP   3. Plugin->install() C:\wamp\www\glpi\front\plugin.form.php:49

[03-Nov-2016 11:24:57 Europe/Paris] PHP   4. plugin_genericobject_install() C:\wamp\www\glpi\inc\plugin.class.php:664

[03-Nov-2016 11:24:57 Europe/Paris] PHP   5. PluginGenericobjectType::install() C:\wamp\www\glpi\plugins\genericobject\hook.php:117

**Comment by btry** [comment] 2016-11-03 10:35
I think a line is missing un the beginining of your dump. 

The plugin generates new classes for the objects you created. They are in glpi/files/_plugins/genericobject/inc/ . One of them should be book.class.php

Ensure it exists and is readable and writeable by your HTTP server.

**Comment by geekson** [comment] 2016-11-03 11:00
There is the line:
[03-Nov-2016 11:24:57 Europe/Paris] PHP Fatal error:  Class 'PluginGenericobjectBook' not found in C:\wamp\www\glpi\plugins\genericobject\inc\type.class.php on line 1931

OK, Thanks! I copied all files from my old backup in glpi/files/_plugins/genericobject/inc/
to the new directory and now it works.

Thanks a lot for your help.

**Comment by trasher** [comment] 2016-11-03 11:01
The migration process should have copied those files; there is an issue here

**Comment by geekson** [comment] 2016-11-03 11:03
I can help you if you want. Do you need any info from my system?

**Comment by trasher** [comment] 2016-11-03 11:26
Seems I was guessing something wrong... I had another plugin in mind :D

Anyways... @geekson the backups files you are talking about were in `glpi/files/_plugins/genericobject`? If so, you removed them before upgrading?

**Comment by geekson** [comment] 2016-11-03 11:32
@trahser yes they were, since I upgraded GLPI to 9.1 there was no  glpi/files/_plugins/genericobject folder.

**Comment by btry** [comment] 2016-11-03 12:48
I think we cannot prevent a crash of the plugin in such case, but we may probably make it more verbose to give some directives to the administrator if the files are not found or usable

- before include : check the file is a file, exists and is readable
- after include : check the expected class exists
- if the class still does not exists after the include then fail with a (long ?) message containing some instructions. 

This way, the admin may be able to solve his problem himsemf, and loose less time.

**Comment by geekson** [comment] 2016-11-03 13:16
Ok thanks for your quick support!

**Comment by btry** [comment] 2016-11-03 13:22
I reopen the issue because I did a implementation if my idea.

@geekson i wish you test this version of the plugin 
https://github.com/btry/genericobject/tree/113_upgrade_issue

Try to upgrade with book.class.php missing. The plugin should fail with an explicit error message. 

Thank you for your feedback.

**Comment by geekson** [comment] 2016-11-03 14:23
**Hi @btry, 

First of I renamed genericobject in_old (FYI I did not stop the service maybe I should) and replace it with the genericobject you gave me,**

**>>KO (blank page)**

[03-Nov-2016 14:45:51 Europe/Paris] PHP Fatal error:  Class 'PluginGenericobjectGlasses3d' not found in C:\wamp\www\glpi\inc\reservationitem.class.php on line 426

[03-Nov-2016 14:45:51 Europe/Paris] PHP Stack trace:

[03-Nov-2016 14:45:51 Europe/Paris] PHP   1. {main}() C:\wamp\www\glpi\ajax\common.tabs.php:0

[03-Nov-2016 14:45:51 Europe/Paris] PHP   2. CommonGLPI::displayStandardTab() C:\wamp\www\glpi\ajax\common.tabs.php:97

[03-Nov-2016 14:45:51 Europe/Paris] PHP   3. ReservationItem::displayTabContentForItem() C:\wamp\www\glpi\inc\commonglpi.class.php:477

[03-Nov-2016 14:45:51 Europe/Paris] PHP   4. ReservationItem::showListSimple() C:\wamp\www\glpi\inc\reservationitem.class.php:750

[03-Nov-2016 14:49:40 Europe/Paris] PHP Fatal error:  Cannot redeclare plugin_init_genericobject() (previously declared in C:\wamp\www\glpi\plugins\genericobject\setup.php:95) in C:\wamp\www\glpi\plugins\genericobject_old\setup.php on line 148

[03-Nov-2016 14:49:40 Europe/Paris] PHP Stack trace:

[03-Nov-2016 14:49:40 Europe/Paris] PHP   1. {main}() C:\wamp\www\glpi\front\plugin.php:0

[03-Nov-2016 14:49:40 Europe/Paris] PHP   2. Plugin->listPlugins() C:\wamp\www\glpi\front\plugin.php:96

[03-Nov-2016 14:49:40 Europe/Paris] PHP   3. Plugin->checkStates() C:\wamp\www\glpi\inc\plugin.class.php:365

[03-Nov-2016 14:49:45 Europe/Paris] PHP Fatal error:  Cannot redeclare plugin_init_genericobject() (previously declared in C:\wamp\www\glpi\plugins\genericobject\setup.php:95) in C:\wamp\www\glpi\plugins\genericobject_old\setup.php on line 148

[03-Nov-2016 14:49:45 Europe/Paris] PHP Stack trace:

[03-Nov-2016 14:49:45 Europe/Paris] PHP   1. {main}() C:\wamp\www\glpi\front\plugin.php:0

[03-Nov-2016 14:49:45 Europe/Paris] PHP   2. Plugin->listPlugins() C:\wamp\www\glpi\front\plugin.php:96

[03-Nov-2016 14:49:45 Europe/Paris] PHP   3. Plugin->checkStates() C:\wamp\www\glpi\inc\plugin.class.php:365

**I had to re-do the upgrade from a clean glpi folder, then I put your folder. As soon as I enabled it nothing worked (blank page), here are the logs:**

03-Nov-2016 15:13:54 Europe/Paris] PHP Fatal error:  Class 'PluginGenericobjectBook' not found in C:\wamp\www\glpi\plugins\genericobject\inc\object.class.php on line 1093

[03-Nov-2016 15:13:54 Europe/Paris] PHP Stack trace:

[03-Nov-2016 15:13:54 Europe/Paris] PHP   1. {main}() C:\wamp\www\glpi\front\plugin.php:0

[03-Nov-2016 15:13:54 Europe/Paris] PHP   2. Html::header() C:\wamp\www\glpi\front\plugin.php:94

[03-Nov-2016 15:13:54 Europe/Paris] PHP   3. PluginGenericobjectObject::getMenuContent() C:\wamp\www\glpi\inc\html.class.php:1387

[03-Nov-2016 15:13:54 Europe/Paris] PHP Fatal error:  Class 'PluginGenericobjectBook' not found in C:\wamp\www\glpi\plugins\genericobject\inc\object.class.php on line 1093

[03-Nov-2016 15:13:54 Europe/Paris] PHP Stack trace:

[03-Nov-2016 15:13:54 Europe/Paris] PHP   1. {main}() C:\wamp\www\glpi\front\central.php:0

[03-Nov-2016 15:13:54 Europe/Paris] PHP   2. Html::header() C:\wamp\www\glpi\front\central.php:73

[03-Nov-2016 15:13:54 Europe/Paris] PHP   3. PluginGenericobjectObject::getMenuContent() C:\wamp\www\glpi\inc\html.class.php:1387

[03-Nov-2016 15:13:59 Europe/Paris] PHP Fatal error:  Class 'PluginGenericobjectBook' not found in C:\wamp\www\glpi\plugins\genericobject\inc\profile.class.php on line 311

[03-Nov-2016 15:13:59 Europe/Paris] PHP Stack trace:

[03-Nov-2016 15:13:59 Europe/Paris] PHP   1. {main}() C:\wamp\www\glpi\front\login.php:0

[03-Nov-2016 15:13:59 Europe/Paris] PHP   2. Auth->Login() C:\wamp\www\glpi\front\login.php:78

[03-Nov-2016 15:13:59 Europe/Paris] PHP   3. Session::init() C:\wamp\www\glpi\inc\auth.class.php:813

[03-Nov-2016 15:13:59 Europe/Paris] PHP   4. Session::changeProfile() C:\wamp\www\glpi\inc\session.class.php:153

[03-Nov-2016 15:13:59 Europe/Paris] PHP   5. Plugin::doHook() C:\wamp\www\glpi\inc\session.class.php:435

[03-Nov-2016 15:13:59 Europe/Paris] PHP   6. call_user_func:{C:\wamp\www\glpi\inc\plugin.class.php:1138}() C:\wamp\www\glpi\inc\plugin.class.php:1138

[03-Nov-2016 15:13:59 Europe/Paris] PHP   7. PluginGenericobjectProfile::changeProfile() C:\wamp\www\glpi\inc\plugin.class.php:1138

[03-Nov-2016 15:13:59 Europe/Paris] PHP   8. PluginGenericobjectProfile::getTypesRights() C:\wamp\www\glpi\plugins\genericobject\inc\profile.class.php:364

Regards,
David

**Comment by btry** [comment] 2016-11-03 14:36
Thank you

In the first try, the folder genericobject_old interfered with the copy we wanted to test.

In the second try, the plugin was disabled. Enabling it triggers a bug elsewhere because the required classes are missing. 

I'll do some tests in a few days. The goal of my change is to display a message before a failure in the upgrade if the classes are missing.

**Comment by btry** [comment] 2016-11-09 22:23
Hi

I fixed an error in my code, but this could not produce your issue. 

With my tests I get the following error message (on upgrade with at least a missing class file).

![image](https://cloud.githubusercontent.com/assets/14139801/20154720/038ecb7c-a6c9-11e6-9f92-e9f19b11a65c.png)

**Comment by btry** [comment] 2016-11-10 06:55
see PR #116

**Comment by geekson** [comment] 2016-11-10 13:25
@btry 
Hi,

I guess if I want to reproduce the issue I have to downgrade my database which is too much time to spend. Thanks a lot for your help.

**Comment by btry** [comment] 2016-11-10 13:34
As I could reproduce myself, I think this is not necessary you consume too much time for this.

I used the following steps, and I think they are sufficient : 
- install Generic Object on a  fresh GLPi 9.1 setup
- create a new object
- change the status of the plugin in DB to force an upgrade
- renamed the class in files/_plugins/genericobject/inc/ to hide it
- tried to upgrade
- Observed the message I added appears

If I rename back the class file, I can upgrade the plugin without any issue.

**Comment by stonebuzz** [comment] 2020-01-27 08:52
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards

**Closed by stonebuzz** 2020-01-27 08:52 UTC
Labels: enhancement, help wanted
