### ISSUE TITLE
Compatibility with FormCreator

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/genericobject#149] opened 2017-07-19 07:13 UTC
See this issue: https://github.com/pluginsGLPI/formcreator/issues/660

FormCreator needs a way to find itemtypes created by GenericObject to populate available itemtypes to build a GLPI Object field.

**Comment by nqb** [comment] 2017-07-20 08:53
@btry : to my mind it's a bug, not an enhancement.

**Comment by btry** [comment] 2017-07-20 09:28
Hi

I would say yes and no. I marked this issue as enhancement because as far as I know noone expects Formcreator to collaborate with Generic Objects (and the reverse too), so this is a feature to make them work together.

Once done, and officially supported, then such issues become a bug.

**Comment by stonebuzz** [comment] 2020-01-27 08:50
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-27 08:50 UTC
Labels: enhancement

**Comment by UbuntitiCH** [comment] 2020-03-20 06:40
I'm interresting on this issue because i need the same functionality. I will see what I can do. But I'm still a novice in php programming. Do you have some learn courses to programming GLPI plugin?

**Comment by btry** [comment] 2020-03-20 08:03
Hi

I think this need requires to have some experience with GLPI and plugins development. If you're new with GLPI development, this may be challenging.

The plugin example : https://github.com/pluginsGLPI/example

documentation for developers : https://glpi-developer-documentation.readthedocs.io/en/master/

Here is an idea to implement the feature:
GLPI has a global array variable $CFG_GLPI. 
Formcreator has a list of itemtypes in the file inc/fields/glpiselectfield.class.php (method getDesignSpecializationField() in the develop branch)
An array in $CFG_GLPI['plugin_formcreator]['glpi_objects'] may be merged with the hard coded list by Formcreator. Generic Object may add its own itemtypes in this array in its post_init function (see documentation).

When Formcreator renders a question of type GLPI Object, it should check the itemtype exists, as Generic Object may be disabled ir uninstalled. All field types have a isPrerequisites() method which was aded recently for this need (see Tag plugin support)
